# window settings
SIZE = '1000x700+200+5'

# labels settings
LABEL_WIDTH = 150
LABEL_HEIGHT = 25
LABEL_X = 10
LABEL_Y = 10

# entry settings
ENTRY_WIDTH = LABEL_WIDTH
ENTRY_HEIGHT = LABEL_HEIGHT
ENTRY_X = LABEL_X + LABEL_WIDTH + 10
ENTRY_Y = LABEL_Y

# buttons settings
BUTTON_WIDTH = LABEL_WIDTH
BUTTON_HEIGHT = LABEL_HEIGHT
BUTTON1_X = LABEL_X
BUTTON2_X = ENTRY_X
BUTTON_Y = LABEL_Y + LABEL_HEIGHT * 7

# table settings
TABLE_WIDTH = 650
TABLE_HEIGHT = 200
TABLE_X = ENTRY_X + ENTRY_WIDTH + 20
TABLE_Y = ENTRY_Y

# graph settings
GRAPH_WIDTH = 980
GRAPH_HEIGHT = 460
GRAPH_X = LABEL_X
GRAPH_Y = BUTTON_Y + BUTTON_HEIGHT + 20

# color settings
LIGHTBLUE = '#64B2CD'
YELLOW = '#DA9833'
